package     = "pywatch4test"
dist_path   = "bin"

cli_path    = "{}/cli.py".format(package)
import_line = "from {}.{} import PathProcessor".format(package, package)
import_path = "{}/{}.py".format(package, package)

header      = "#!/usr/bin/env python\n" \
              "# Do not edit this file.\n" \
              "# This file is generated from `scripts/generate_bin.py`.\n" \
              "# ----------------------------- \n" \
              "# Author: Thada Wangthammang (mildronize@gmail.com) \n" \
              "# GitHub: https://github.com/mildronize/pywatch4test\n" \


with open(cli_path) as cli_file:
    cli_lines = cli_file.read().splitlines()
    inserting_line = cli_lines.index(import_line)
    dist_file = open('{}/{}'.format(dist_path, package), 'w')
    dist_file.write(header + '\n')

    # Write cli code before inserting line
    for i in range(inserting_line):
        dist_file.write(cli_lines[i] + '\n')

    # Insert the importing file
    with open(import_path) as import_file:
        for line in import_file:
            dist_file.write(line)

    # Write the rest of cli code
    for i in range(inserting_line+1 , len(cli_lines)):
        dist_file.write(cli_lines[i] + '\n')

    dist_file.close()

